# Generated by Django 2.1.4 on 2018-12-14 01:45

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('usr_id', models.ForeignKey(on_delete=builtins.id, to='core.User')),
            ],
        ),
    ]
