# Generated by Django 2.1.4 on 2018-12-14 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181214_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='usr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
